### ISSUE TITLE
Support for running inside containers

### ISSUE THREAD

**Issue by akaibukai** [fabiospampinato/vscode-commands#41] opened 2022-02-22 02:42 UTC
Hello,

In a way to circumvent the following [issue (allowing shortcuts)](https://github.com/fabiospampinato/vscode-terminals/issues/65) of Terminals Manager (BTW thank you for all your work)..

I discovered that plugin.

However it simply doesn't work when using VS Code Remote Containers feature (aka devcontainer).

I don't know why it's not possible to install it inside remote containers but is it possible to make it work?

Thank you very much.

**Comment by fabiospampinato** [comment] 2022-11-15 21:13
I think extensions have to explicitly say that they support remote containers or something, I should look into this, I'm not familiar with how this works.

**Comment by fabiospampinato** [comment] 2024-03-15 23:13
Closing as duplicate of #35

**Closed by fabiospampinato** 2024-03-15 23:13 UTC
Labels: enhancement
